name: dmrazzy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dmrazzy
      run: docker build . --file dmrazzyfile --tag my-image-name:$(date +%s)
